basePath: /api
definitions:
  handler.createAccountRequestBody:
    properties:
      name:
        type: string
    type: object
  handler.createUserRequestBody:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.deleteAccountRequestBody:
    properties:
      name:
        type: string
    type: object
  handler.makeTransferRequestBody:
    properties:
      amount:
        type: integer
      payee_account_id:
        type: integer
      sender_account_id:
        type: integer
    type: object
  handler.userLoginRequestBody:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  transfer.Transfer:
    properties:
      amount:
        type: integer
      date:
        type: string
      payeeAccountId:
        type: integer
      payeeUsername:
        type: string
      senderAccountId:
        type: integer
      transferType:
        type: string
    type: object
  views.AccountResponse:
    properties:
      balance:
        type: integer
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  views.DepositResponse:
    properties:
      amount:
        type: integer
      date:
        type: string
      payee_account_id:
        type: integer
      sender_account_id:
        type: integer
      sender_username:
        type: string
    type: object
  views.TransferResponse:
    properties:
      amount:
        type: integer
      date:
        type: string
      payee_account_id:
        type: integer
      payee_username:
        type: string
      sender_account_id:
        type: integer
      transfer_type:
        type: string
    type: object
  views.UserResponse:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Mock Banking Application
  title: Mock Banking Application API
  version: "1.0"
paths:
  /account:
    delete:
      consumes:
      - application/json
      description: Delete a bank account with specific name
      parameters:
      - description: Account name
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.deleteAccountRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted
          schema:
            type: string
        "400":
          description: Invalid Request Body
          schema:
            type: string
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Delete a bank account
      tags:
      - Bank Account
    post:
      consumes:
      - application/json
      description: Create a new bank account with specific name
      parameters:
      - description: Account name
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.createAccountRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created
          schema:
            $ref: '#/definitions/views.AccountResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Create a bank account
      tags:
      - Bank Account
  /accounts:
    get:
      description: Get all bank accounts user have
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved
          schema:
            items:
              $ref: '#/definitions/views.AccountResponse'
            type: array
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Get all bank accounts
      tags:
      - Bank Account
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login into account
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.userLoginRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
          schema:
            type: string
        "400":
          description: Invalid Request Body
          schema:
            type: string
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Login
      tags:
      - Auth
  /auth/logout:
    post:
      description: Logout from account
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            type: string
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
      summary: Logout
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.createUserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully signed up
          schema:
            $ref: '#/definitions/views.UserResponse'
        "400":
          description: Invalid Request Body
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Register
      tags:
      - Auth
  /deposits:
    get:
      description: Get all deposits that have been made to user accounts from other
        clients
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved
          schema:
            items:
              $ref: '#/definitions/views.DepositResponse'
            type: array
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Get all deposits
      tags:
      - Deposit
  /transfer:
    post:
      consumes:
      - application/json
      description: Make a transfer between own/clients accounts
      parameters:
      - description: Transfer data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.makeTransferRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully made a transfer
          schema:
            $ref: '#/definitions/views.TransferResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Make a transfer
      tags:
      - Transfer
  /transfers:
    get:
      description: Get all transfers user have made between own/other accounts
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved
          schema:
            items:
              $ref: '#/definitions/transfer.Transfer'
            type: array
        "401":
          description: Authorization information is missing or invalid
          schema:
            type: string
        "500":
          description: Unexpected error
          schema:
            type: string
      summary: Get all transfers
      tags:
      - Transfer
swagger: "2.0"
